### ISSUE TITLE
Angular 6.0.0 Compatability

### ISSUE THREAD

**Issue by martinabrahams** [Enngage/kentico-cloud-js#61]
I get the following error when trying to build an Angular 6 project which contains the delivery sdk.

```
ERROR in ./node_modules/kentico-cloud-delivery/node_modules/parse5/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/martya/…/node_modules/parse5/lib/parser'
ERROR in ./node_modules/kentico-cloud-delivery/node_modules/parse5/lib/sax/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/martya/…/node_modules/kentico-cloud-delivery/node_modules/parse5/lib/sax'
ERROR in ./node_modules/kentico-cloud-delivery/node_modules/parse5/lib/sax/dev_null_stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/martya/…/node_modules/kentico-cloud-delivery/node_modules/parse5/lib/sax'
ERROR in ./node_modules/kentico-cloud-delivery/node_modules/parse5/lib/serializer/serializer_stream.js
Module not found: Error: Can't resolve 'stream' in '/Users/martya/…/node_modules/kentico-cloud-delivery/node_modules/parse5/lib/serializer'
```

In my research into the issue I noticed that @Enngage has lodged a ticket about this on the official angular project. It seems like it's an underlying issue with Angular, however it's worth lodging an issue here so other's can see what's going on. 

The only workaround which I've found is to install the stream package separately via npm `npm install stream`. This solves the issue for now but it would good if there's a better way.

**Comment by Enngage** [comment]
Hi, have you seen our sample [Angular 6 ](https://github.com/Enngage/KenticoCloudSampleAngularApp)app ? It's currently running on Angular 6. There is an issue with Angular CLI which ignores dynamic require expressions which essentially means that it tries to include node specific, which of course, fails. 

The workaround is to tell your app to use 'Browser' specific package which you can do in the `ts.config.json`. I have described this process in the main readme of the angular app above. 

Additionally, you can see the code also here https://github.com/Enngage/KenticoCloudSampleAngularApp/blob/master/tsconfig.json#L16

Let me know how that works!

**Comment by martinabrahams** [comment]
That worked perfectly, thanks! 

Also in my case I'm running Angular Universal which runs seperate tsconfigs for server (nodejs) and browser, so I set the path as the non browser bundle on the server and it seems to work perfectly.

**Comment by Enngage** [comment]
Awesome, glad to hear it! Thanks for the note, I've yet to use Angular Universal so I might incorporate that into the Angular example :-)

**Comment by Enngage** [comment]
I was finally able to update to `parse5` which strips the dependency out of Node so this should no longer be an issue. Though, the `parse5` is relatively large library so I would recommend using browser specific package if possible anyway. (200KB vs 370KB)

**Comment by Enngage** [comment]
@r3plica Have you seen the sample Angular application? You can see how tsconfig.json looks like right there: https://github.com/Enngage/KenticoCloudSampleAngularApp#angular-6-support

**Comment by r3plica** [comment]
Yeah and I used it to build my application, but as martin has done, I am trying to create a Universal application. I think I understand what he has done (just testing now). Instead of using:
https://github.com/Enngage/KenticoCloudSampleAngularApp/blob/master/tsconfig.json#L17
I changed it to: 

`"node_modules/kentico-cloud-delivery/_bundles/kentico-cloud-delivery-sdk.umd.min.js"`

But that also does not work. I get an error stating:

`ERROR in src/app/core/models/scanario.ts(18,26): error TS2694: Namespace '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/fields/field-types".Fields' has no exported member 'UrlSlug'.
src/app/core/models/scanario.ts(19,27): error TS2694: Namespace '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/fields/field-types".Fields' has no exported member 'UrlSlug'.
src/app/core/models/tech-made-simple.ts(5,30): error TS2694: Namespace '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/fields/field-types".Fields' has no exported member 'RichText'.
src/app/core/models/tech-made-simple.ts(7,32): error TS2694: Namespace '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/fields/field-types".Fields' has no exported member 'RichText'.
src/app/home/home.component.ts(6,26): error TS2305: Module '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/index"' has no exported member 'CloudError'.
src/app/buying-guide/pillar.component.ts(7,26): error TS2305: Module '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/index"' has no exported member 'CloudError'.
src/app/buying-guide/pillar.component.ts(69,68): error TS2339: Property 'taxonomyTerms' does not exist on type 'TextField'.
src/app/buying-guide/pillar.component.ts(71,94): error TS2339: Property 'taxonomyTerms' does not exist on type 'TextField'.
src/app/buying-guide/pillar.component.ts(77,99): error TS2339: Property 'taxonomyTerms' does not exist on type 'TextField'.
src/app/buying-guide/cluster.component.ts(7,26): error TS2305: Module '"C:/Users/JaymieJeffrey/Documents/GitHub/pickyourbest/node_modules/kentico-cloud-delivery/_commonjs/index"'
has no exported member 'CloudError'.`

**Comment by Enngage** [comment]
Okey, so for Angular universal take a look at this sample application: https://github.com/Enngage/kentico-cloud-js-angular-universal-starter 

It's pretty much the default starter provided by Angular team and only modified to load some data from Kentico Cloud. Can you try using that application on your end? You may notice that in order to fully leverage Angular universal, you need to use Angular's HttpClient for we provided a specific service. 

Take a look at https://github.com/Enngage/kentico-cloud-js-angular-universal-starter/blob/master/src/app/home/home.component.ts#L21 

Also, you need to use beta version of this library as you can see here: https://github.com/Enngage/kentico-cloud-js-angular-universal-starter/blob/master/package.json#L37 

And finally, no extra configuration in tsconfig seems to be necessary here. The original issue in this thread was caused by Angular cli not properly building an application, but that seems to be fixed now.

**Comment by r3plica** [comment]
Thanks for this, just a quick question. I created a factory to provide the delivery client. It looks like this:

`
import { DeliveryClient, TypeResolver } from 'kentico-cloud-delivery';

import { Attribute } from '../models/attribute';
import { Pillar } from '../models/pillar';
import { Scenario } from '../models/scanario';
import { TechMadeSimple } from '../models/tech-made-simple';

export const KenticoClientService = {
  provide: DeliveryClient,
  useFactory: KenticoServiceFactory,
  deps: []
};

export function KenticoServiceFactory() {
  return new DeliveryClient({
    projectId: 'my-project-id',
    typeResolvers: [
      new TypeResolver('attribute', () => new Attribute()),
      new TypeResolver('pillar', () => new Pillar()),
      new TypeResolver('scenario', () => new Scenario()),
      new TypeResolver('tech_made_simple', () => new TechMadeSimple()),
    ]
  });
}
`

Any idea how to add the angularHttpService to that?

**Comment by Enngage** [comment]
So, in this case you need to provide the `angularHttpService` as a dependency through your `deps` in factory and then add this as a parameter to your `KenticoServiceFactory` function. Some information about this is in Angular docs here: https://angular.io/guide/dependency-injection-in-action#defining-providers 

Hope that helps.

**Comment by r3plica** [comment]
When you say `angularHttpService`, do you mean `HttpClient`?

**Comment by r3plica** [comment]
I have changed my service to:

import { Injectable } from '@angular/core';

import { IDeliveryClient, DeliveryClient, TypeResolver } from 'kentico-cloud-delivery';
import { AngularHttpService } from 'kentico-cloud-angular-http-service';

import { Attribute } from '../models/attribute';
import { Pillar } from '../models/pillar';
import { Scenario } from '../models/scanario';
import { TechMadeSimple } from '../models/tech-made-simple';
import { WhatToLookFor } from '../models/what-to-look-for';
import { Blog } from '../models/blog';
import { QuickThree } from '../models/quick-three';

@Injectable({ providedIn: 'root' })
export class KenticoClientService {
  deliveryClient: IDeliveryClient

  constructor(angularHttpService: AngularHttpService) {
    this.deliveryClient = new DeliveryClient({
      projectId: 'da5abe9f-fdad-4168-97cd-b3464be2ccb9',
      httpService: angularHttpService,
      typeResolvers: [
      new TypeResolver('attribute', () => new Attribute()),
      new TypeResolver('pillar', () => new Pillar()),
      new TypeResolver('scenario', () => new Scenario()),
      new TypeResolver('tech_made_simple', () => new TechMadeSimple()),
      new TypeResolver('what_to_look_for', () => new WhatToLookFor()),
      new TypeResolver('blog', () => new Blog()),
      new TypeResolver('quick_three', () => new QuickThree()),
      ]
    });
  }
}

does that look right to you?

**Comment by r3plica** [comment]
Using that service, it does work.

**Comment by Enngage** [comment]
Yes, that is the correct use of the service.
